In [6]:
import pandas as pd

from sklearn.decomposition import PCA

import pickle

## Adding SVD

In [2]:
df = pd.read_pickle('../Data/01_tf_idf_and_features')

In [3]:
df.head(2)

,company_name,job_title,listed_items,posting_url,00,000,000ad_hoc,000best_practice,000machine_learning,000skill_experience,...,zookeeperend_end,zoom,zoura,zuckerberg,zurb,zvs,zweigwhite,zymergen,zymo,zynga
0,Gap Inc. Corporate,"Software Engineer, Price Execution",write build product according business need co...,https://www.indeed.com/rc/clk?jk=77d524a7cf198...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,WrkShp,Business Analyst,closely product assist investigation deep dive...,https://www.indeed.com/company/WrkShp/jobs/Bus...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
pca = PCA(n_components=100)
pca.fit(df.iloc[:,4:])
tf_idf_df = pd.DataFrame(pca.transform(df.iloc[:,4:]))

In [7]:
pickle_out = open('../Tools_and_models/pca_tool',"wb")
pickle.dump(pca, pickle_out)
pickle_out.close()

In [6]:
df = df.iloc[:,:4].merge(tf_idf_df,left_index=True,right_index=True)

In [7]:
df.head()

,company_name,job_title,listed_items,posting_url,0,1,2,3,4,5,...,90,91,92,93,94,95,96,97,98,99
0,Gap Inc. Corporate,"Software Engineer, Price Execution",write build product according business need co...,https://www.indeed.com/rc/clk?jk=77d524a7cf198...,-0.019090,0.040501,-0.112431,0.103970,-0.106989,-0.026306,...,0.002396,-0.015071,-0.013495,0.002928,-0.015414,-0.079520,0.011122,0.001284,0.034969,0.043990
1,WrkShp,Business Analyst,closely product assist investigation deep dive...,https://www.indeed.com/company/WrkShp/jobs/Bus...,-0.010927,0.164458,0.122718,-0.153918,-0.014575,-0.100430,...,-0.043133,-0.011965,0.003011,0.034008,0.033314,0.005770,-0.075077,0.064688,-0.001266,-0.017888
2,Ceres Imaging,Image Processing: GIS / Remote Sensing Analyst,proficiency gi software e g arcgis envi experi...,https://www.indeed.com/rc/clk?jk=8f702cd563785...,0.064959,-0.130597,-0.012915,0.000326,-0.020176,-0.031159,...,0.072121,0.020364,-0.057734,-0.022652,0.023028,-0.026972,0.045027,0.024582,0.061548,-0.015834
3,Deloitte,"Analyst, Strategy and Research",effectively interpret client request use tacti...,https://www.indeed.com/rc/clk?jk=8a288a5c5a09d...,-0.101598,-0.037274,0.040113,-0.012223,-0.040209,0.047943,...,-0.014547,0.000741,0.046328,0.090302,0.034393,-0.004047,-0.007654,-0.034240,0.002480,-0.023435
4,Turing Video,Computer Vision Software Engineer,maintain existing software system implement co...,https://www.indeed.com/rc/clk?jk=fcf308f2fee2a...,0.149299,0.010717,-0.028881,0.143432,-0.067979,0.051231,...,-0.041999,0.037092,-0.027940,-0.001335,-0.017423,0.007670,-0.051687,-0.014250,-0.029634,-0.004588

In [8]:
df.shape

(2964, 104)

In [9]:
df.to_pickle('../Data/01_sf_recommender_pca')