In [1]:
import pandas as pd

from sklearn.decomposition import PCA

import pickle

## Adding PCA
Reducing dimensionality for faster computation in the flask app.

In [2]:
df = pd.read_pickle('../Data/01_tf_idf_and_features')

In [3]:
df.head(2)

,company_name,job_title,listed_items,posting_url,aa,aaa,aaai,aac,aad,aami,...,zoura,zpn,zuckerberg,zurb,zvs,zweigwhite,zymergen,zymo,zynga,ºc
0,Gap Inc. Corporate,"Software Engineer, Price Execution",write build product according business conduct...,https://www.indeed.com/rc/clk?jk=77d524a7cf198...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,WrkShp,Business Analyst,closely product assist investigation deep dive...,https://www.indeed.com/company/WrkShp/jobs/Bus...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
pca = PCA(n_components=300)
pca.fit(df.iloc[:,4:])
tf_idf_df = pd.DataFrame(pca.transform(df.iloc[:,4:]))

In [5]:
pickle_out = open('../Tools_and_models/pca_tool',"wb")
pickle.dump(pca, pickle_out)
pickle_out.close()

In [6]:
df = df.iloc[:,:4].merge(tf_idf_df,left_index=True,right_index=True)

In [7]:
df.head()

,company_name,job_title,listed_items,posting_url,0,1,2,3,4,5,...,290,291,292,293,294,295,296,297,298,299
0,Gap Inc. Corporate,"Software Engineer, Price Execution",write build product according business conduct...,https://www.indeed.com/rc/clk?jk=77d524a7cf198...,-0.018077,0.014864,0.117981,0.040068,-0.062345,0.038817,...,-0.014063,-0.019327,0.013030,0.008991,0.003695,-0.012031,0.005944,0.020383,0.009977,-0.004942
1,WrkShp,Business Analyst,closely product assist investigation deep dive...,https://www.indeed.com/company/WrkShp/jobs/Bus...,-0.049036,0.180958,-0.111539,0.089243,-0.110111,-0.009823,...,0.020357,0.018804,-0.018694,0.023452,-0.002981,0.039731,0.034997,-0.020702,-0.001777,-0.041647
2,Ceres Imaging,Image Processing: GIS / Remote Sensing Analyst,proficiency gi e g arcgis envi processing prod...,https://www.indeed.com/rc/clk?jk=8f702cd563785...,0.068104,-0.108209,-0.024293,0.013824,0.080689,-0.107695,...,0.014435,-0.006349,-0.022195,0.007054,-0.001135,-0.001025,-0.009957,-0.005164,0.004571,-0.005716
3,Deloitte,"Analyst, Strategy and Research",effectively interpret client request use tacti...,https://www.indeed.com/rc/clk?jk=8a288a5c5a09d...,-0.076938,-0.030794,-0.033607,0.040571,0.034268,-0.016858,...,0.002196,0.015415,0.031909,0.051545,0.008766,-0.005510,0.010462,0.027878,-0.020657,-0.001136
4,Turing Video,Computer Vision Software Engineer,maintain existing implement algorithm necessar...,https://www.indeed.com/rc/clk?jk=fcf308f2fee2a...,0.144809,0.012746,0.025459,-0.029213,0.056539,0.029222,...,-0.057134,0.033395,-0.033605,0.011401,-0.020123,0.008876,-0.033616,-0.039308,0.006560,0.051977

In [8]:
df.shape

(3364, 304)

In [9]:
df.to_pickle('../Data/01_sf_recommender_pca')